version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: retrovault-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: retrovault_db
      POSTGRES_USER: sysdba
      POSTGRES_PASSWORD: masterkey
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: